name="Yuvaraj" 
print(name) 
len(name)
print(len(name)) 
name[4] 
print(name[4]) 
name[4:8] 
print(name[4:8])
name[4::8] 
print(name[4::8]) 
name[-4]
print(name[-4]) 
name.upper() 
print(name.upper()) 
name.lower() 
print(name.lower())