import math
def print_thrice(bruce):
    print(bruce)
    print(bruce)
    print(bruce)
print_thrice("Silly Guy")  
print_thrice("Silly Guy"  *5)
print_thrice(105) 
print_thrice(math.sin) 
print_thrice(math.pow)
print_thrice(math.cos) 
print_thrice(math.tan) 
print_thrice(math.pi) 
print_thrice(math.log) 
print_thrice(math.exp) 
print_thrice(math.tan(math.pi)) 
print_thrice(math.log(math.pi)) 
print_thrice(math.sin(math.pi)) 
print_thrice(math.cos(math.pi)) 
print_thrice(math.exp(math.pi)) 
bruce="Yuvi is a good boy" 
print_thrice(bruce)